/* GENERATED by scripts/build-tokens.mjs — do not edit.
 * Source of truth: design-system/tokens.json (`encoding`)
 */

export const SEVERITIES = ['blocker', 'violation', 'advisory', 'manual', 'checked'] as const;

export type Severity = (typeof SEVERITIES)[number];

export interface SeverityEncoding {
  /** text-decoration-style used for the inline underline */
  underline: string;
  /** glyph key; maps to an inline SVG, never a bare colour swatch */
  glyph: string;
  /** always rendered as visible text — this is the primary channel */
  label: string;
  /** what this means in WCAG terms */
  wcag: string;
}

export const SEVERITY_ENCODING: Record<Severity, SeverityEncoding> = {
  "blocker": {
    "underline": "double",
    "glyph": "octagon",
    "label": "Blocks access",
    "wcag": "Fails Level A"
  },
  "violation": {
    "underline": "wavy",
    "glyph": "triangle",
    "label": "Fails AA",
    "wcag": "Fails Level AA"
  },
  "advisory": {
    "underline": "dotted",
    "glyph": "circle-i",
    "label": "Advisory",
    "wcag": "AAA / best practice"
  },
  "manual": {
    "underline": "dashed",
    "glyph": "diamond-q",
    "label": "Needs your call",
    "wcag": "Not machine-decidable"
  },
  "checked": {
    "underline": "none",
    "glyph": "check",
    "label": "Rule passed",
    "wcag": "No finding for this rule"
  }
} as const;

/** Sort order for triage: what blocks a user comes before what merely warns. */
export const SEVERITY_RANK: Record<Severity, number> = {
  blocker: 0,
  violation: 1,
  advisory: 2,
  manual: 3,
  checked: 4,
};
