#!/usr/bin/env node
/**
 * Generates design-system/preview.html from the REAL components.
 *
 * The previous preview was hand-written markup that imitated the components.
 * Dumping the accessibility tree against it showed four buttons all named
 * "Dismiss", cards with no accessible name and no live region — none of which
 * was true of the components themselves. It was verifying fiction.
 *
 * So this renders the actual React tree with react-dom/server, then ships a
 * hydrating bundle so the page is genuinely interactive. The preview cannot
 * drift from the components because it IS the components.
 *
 *   node scripts/build-preview.mjs
 */

import { build } from 'esbuild';
import { renderToString } from 'react-dom/server';
import { writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { createElement } from 'react';

const HERE = dirname(fileURLToPath(import.meta.url));
const DS = resolve(HERE, '../design-system');

/* Bundle the client entry (esbuild handles the TSX the SSR import also needs). */
const OUT_DIR = resolve(DS, 'preview');
mkdirSync(OUT_DIR, { recursive: true });

await build({
  entryPoints: [resolve(HERE, 'harness/entry.tsx')],
  bundle: true,
  format: 'esm',
  target: 'es2022',
  jsx: 'automatic',
  minify: true,
  outfile: resolve(OUT_DIR, 'harness.js'),
  logLevel: 'warning',
});

/* Server-render the same tree so the page has content without JavaScript.
 * The component tree is compiled to a real file rather than a data: URL,
 * because a data: module cannot resolve bare specifiers like "react". */
const SSR_TMP = resolve(OUT_DIR, '.ssr.mjs');

await build({
  entryPoints: [resolve(HERE, 'harness/App.tsx')],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  jsx: 'automatic',
  packages: 'external',
  outfile: SSR_TMP,
  logLevel: 'warning',
});

let markup;
try {
  const { App } = await import(pathToFileURL(SSR_TMP).href);
  markup = renderToString(createElement(App));
} finally {
  rmSync(SSR_TMP, { force: true });
}

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Ada-editor design system preview</title>
<!-- GENERATED by scripts/build-preview.mjs from the real components. Do not edit. -->
<link rel="stylesheet" href="./tokens.css">
<link rel="stylesheet" href="./primitives/primitives.css">
<style>
  /* Preview harness only. Not part of the design system. */
  .harness { display: grid; grid-template-columns: minmax(0,1fr) auto; gap: var(--ada-space-6); align-items: start; padding: var(--ada-space-5); }
  .harness__doc { background: var(--ada-surface-canvas); }
  .harness__doc:focus-visible, [tabindex="-1"]:focus-visible { outline: var(--ada-focus-width) solid var(--ada-focus-ring); outline-offset: var(--ada-focus-offset); }
  h1 { font-size: var(--ada-type-size-xl); margin: 0 0 var(--ada-space-4); }
  .grayscale { filter: grayscale(1); }
  .ada-underline[data-revealed="true"] { background: var(--ada-surface-sunken); }
</style>
</head>
<body>
<div id="root">${markup}</div>
<script type="module" src="./preview/harness.js"></script>
</body>
</html>
`;

writeFileSync(resolve(DS, 'preview.html'), html);
console.log('wrote design-system/preview.html and design-system/preview/harness.js');
