#!/usr/bin/env node
/**
 * Generates design-system/tokens.css and design-system/tailwind-theme.css from
 * design-system/tokens.json. tokens.json is the only source of truth — never
 * hand-edit the generated CSS.
 *
 *   node scripts/build-tokens.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const DS = resolve(HERE, '../design-system');
const doc = JSON.parse(readFileSync(resolve(DS, 'tokens.json'), 'utf8'));

const getPath = (o, p) => p.split('.').reduce((n, k) => (n == null ? undefined : n[k]), o);
const deref = (v) => {
  if (typeof v !== 'string') return v;
  const m = v.match(/^\{(.+)\}$/);
  return m ? deref(getPath(doc, m[1]).$value) : v;
};

const walk = function* (node, trail = []) {
  if (node && typeof node === 'object') {
    if ('$value' in node) return yield { path: trail, token: node };
    for (const [k, c] of Object.entries(node)) {
      if (k.startsWith('$')) continue;
      yield* walk(c, [...trail, k]);
    }
  }
};

// Drops empty segments (so an empty prefix cannot emit `--ada--foo`) and
// kebab-cases camelCase keys so `lineHeight` becomes `line-height`.
const varName = (parts) =>
  `--ada-${parts
    .filter(Boolean)
    .map((p) => p.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase())
    .join('-')}`;

const themeBlock = (theme, indent = '  ') =>
  [...walk(doc.semantic[theme])]
    .map(({ path, token }) => `${indent}${varName(path)}: ${deref(token.$value)};`)
    .join('\n');

const scaleBlock = (root, prefix) =>
  [...walk(doc[root])].map(({ path, token }) => `  ${varName([prefix, ...path])}: ${deref(token.$value)};`).join('\n');

const encodingBlock = Object.entries(doc.encoding)
  .filter(([k]) => !k.startsWith('$'))
  .flatMap(([name, spec]) => [
    `  --ada-underline-${name}: ${spec.underline};`,
    `  --ada-glyph-${name}: "${spec.glyph}";`,
  ])
  .join('\n');

const css = `/* GENERATED by scripts/build-tokens.mjs — do not edit.
 * Source of truth: design-system/tokens.json
 *
 * Colour is a redundant channel in this system. Severity meaning is carried by
 * --ada-underline-* (shape), the glyph, and a visible text label. If you are
 * reaching for a severity colour to communicate something, you are using the
 * wrong channel.
 */

:root {
  color-scheme: light dark;

  /* primitive ramps — do not reference these from components */
${scaleBlock('primitive', 'c')}

  /* dimensions */
${scaleBlock('dimension', '')}

  /* typography */
${scaleBlock('typography', 'type')}

  /* severity encoding — the channels that actually carry meaning */
${encodingBlock}

  /* motion */
  --ada-motion-fast: 120ms;
  --ada-motion-base: 200ms;
  --ada-motion-ease: cubic-bezier(0.2, 0, 0, 1);

  /* semantic: light */
${themeBlock('light')}
}

/* Dark by system preference, unless the user has pinned light. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
${themeBlock('dark', '    ')}
  }
}

/* Dark pinned explicitly. */
:root[data-theme="dark"] {
${themeBlock('dark')}
}

/* Windows High Contrast / forced-colors. Hand every colour back to the OS:
 * in forced-colors mode our palette is not ours to choose. */
@media (forced-colors: active) {
  :root {
    --ada-surface-canvas: Canvas;
    --ada-surface-raised: Canvas;
    --ada-surface-sunken: Canvas;
    --ada-surface-overlay: Canvas;
    --ada-text-primary: CanvasText;
    --ada-text-secondary: CanvasText;
    --ada-text-tertiary: CanvasText;
    --ada-text-inverse: Canvas;
    --ada-border-subtle: CanvasText;
    --ada-border-default: CanvasText;
    --ada-border-control: CanvasText;
    --ada-focus-ring: Highlight;
    --ada-focus-halo: Canvas;
    --ada-action-primary-bg: ButtonFace;
    --ada-action-primary-fg: ButtonText;
    --ada-action-secondary-bg: ButtonFace;
    --ada-action-secondary-fg: ButtonText;
    --ada-severity-blocker-fg: CanvasText;
    --ada-severity-violation-fg: CanvasText;
    --ada-severity-advisory-fg: CanvasText;
    --ada-severity-manual-fg: CanvasText;
    --ada-severity-checked-fg: CanvasText;
    --ada-severity-blocker-bg: Canvas;
    --ada-severity-violation-bg: Canvas;
    --ada-severity-advisory-bg: Canvas;
    --ada-severity-manual-bg: Canvas;
    --ada-severity-checked-bg: Canvas;
  }
  /* This is precisely why severity is encoded by underline shape: in
   * forced-colors every severity is the same colour, and the system still works. */
}

@media (prefers-reduced-motion: reduce) {
  :root {
    --ada-motion-fast: 0ms;
    --ada-motion-base: 0ms;
  }
}

/* ---------- base layer ---------- */

*,
*::before,
*::after { box-sizing: border-box; }

body {
  background: var(--ada-surface-canvas);
  color: var(--ada-text-primary);
  font-family: var(--ada-type-family-ui);
  font-size: var(--ada-type-size-base);   /* 16px floor, not overridable */
  line-height: var(--ada-type-line-height-body);
}

/* One focus ring for the whole system. Dual-tone so it reads on any surface,
 * and it satisfies SC 2.4.13 Focus Appearance (AAA), not merely 2.4.7. */
:where(a, button, input, select, textarea, [tabindex]):focus-visible {
  outline: var(--ada-focus-width) solid var(--ada-focus-ring);
  outline-offset: var(--ada-focus-offset);
  box-shadow: 0 0 0 var(--ada-focus-halo-width) var(--ada-focus-halo);
}

/* Never remove the ring without replacing it. */
:where(a, button, input, select, textarea, [tabindex]):focus:not(:focus-visible) {
  outline: none;
}
`;

writeFileSync(resolve(DS, 'tokens.css'), css);

/* ---------- Tailwind v4 @theme mapping ---------- */

const tw = `/* GENERATED by scripts/build-tokens.mjs — do not edit.
 *
 * Tailwind v4 is CSS-first, so the design tokens ARE the theme. There is no
 * JS config to drift out of sync with tokens.json.
 *
 *   @import "tailwindcss";
 *   @import "./design-system/tokens.css";
 *   @import "./design-system/tailwind-theme.css";
 */

@theme inline {
  --color-canvas: var(--ada-surface-canvas);
  --color-raised: var(--ada-surface-raised);
  --color-sunken: var(--ada-surface-sunken);
  --color-overlay: var(--ada-surface-overlay);

  --color-fg: var(--ada-text-primary);
  --color-fg-muted: var(--ada-text-secondary);
  --color-fg-subtle: var(--ada-text-tertiary);
  --color-fg-inverse: var(--ada-text-inverse);

  --color-border-subtle: var(--ada-border-subtle);
  --color-border-default: var(--ada-border-default);
  --color-border-control: var(--ada-border-control);

  --color-focus: var(--ada-focus-ring);

  --color-blocker: var(--ada-severity-blocker-fg);
  --color-blocker-bg: var(--ada-severity-blocker-bg);
  --color-violation: var(--ada-severity-violation-fg);
  --color-violation-bg: var(--ada-severity-violation-bg);
  --color-advisory: var(--ada-severity-advisory-fg);
  --color-advisory-bg: var(--ada-severity-advisory-bg);
  --color-manual: var(--ada-severity-manual-fg);
  --color-manual-bg: var(--ada-severity-manual-bg);
  --color-checked: var(--ada-severity-checked-fg);
  --color-checked-bg: var(--ada-severity-checked-bg);

  --radius-sm: var(--ada-radius-sm);
  --radius-md: var(--ada-radius-md);
  --radius-lg: var(--ada-radius-lg);

  --spacing-1: var(--ada-space-1);
  --spacing-2: var(--ada-space-2);
  --spacing-3: var(--ada-space-3);
  --spacing-4: var(--ada-space-4);
  --spacing-5: var(--ada-space-5);
  --spacing-6: var(--ada-space-6);

  --font-ui: var(--ada-type-family-ui);
  --font-doc: var(--ada-type-family-doc);
  --font-mono: var(--ada-type-family-mono);
}
`;

writeFileSync(resolve(DS, 'tailwind-theme.css'), tw);
/* ---------- severity encoding -> TypeScript ---------- */
/* Generated so the encoding table cannot drift from tokens.json. If you want a
 * new severity, add it to tokens.json and rebuild; do not hand-write it here. */

const severities = Object.entries(doc.encoding).filter(([k]) => !k.startsWith('$'));

const ts = `/* GENERATED by scripts/build-tokens.mjs — do not edit.
 * Source of truth: design-system/tokens.json (\`encoding\`)
 */

export const SEVERITIES = [${severities.map(([k]) => `'${k}'`).join(', ')}] as const;

export type Severity = (typeof SEVERITIES)[number];

export interface SeverityEncoding {
  /** text-decoration-style used for the inline underline */
  underline: string;
  /** glyph key; maps to an inline SVG, never a bare colour swatch */
  glyph: string;
  /** always rendered as visible text — this is the primary channel */
  label: string;
  /** what this means in WCAG terms */
  wcag: string;
}

export const SEVERITY_ENCODING: Record<Severity, SeverityEncoding> = ${JSON.stringify(
  Object.fromEntries(
    severities.map(([k, v]) => [k, { underline: v.underline, glyph: v.glyph, label: v.label, wcag: v.wcag }])
  ),
  null,
  2
)} as const;

/** Sort order for triage: what blocks a user comes before what merely warns. */
export const SEVERITY_RANK: Record<Severity, number> = {
${severities.map(([k], i) => `  ${k}: ${i},`).join('\n')}
};
`;

writeFileSync(resolve(DS, 'primitives/severity.ts'), ts);

console.log('wrote design-system/tokens.css, tailwind-theme.css and primitives/severity.ts');
